#!/bin/bash

xset +dpms
xset dpms 0 0 300
xset s noblank
xset s off
DISPLAY=:0 xrandr --output HDMI-1 --rotate left
TOUCH_DEVICE_ID=$(xinput list | grep -iE "id=[0-9]+" | grep -i "Waveshare" | grep -oP 'id=\K[0-9]+')
if [ -n "$TOUCH_DEVICE_ID" ]; then
    DISPLAY=:0 xinput set-prop "$TOUCH_DEVICE_ID" 'Coordinate Transformation Matrix' 0 -1 1 1 0 0 0 0 1
else
    echo "Touch device not found."
fi
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
chromium-browser --force-dark-mode --noerrdialogs --disable-infobars --disable-pinch --remote-debugging-port=9222 --check-for-update-interval=31536000 --force-device-scale-factor=1.322 --kiosk ___HOME_ASSISTANT_URL___ &
